### ISSUE TITLE
External rabbitmq instance without access to "/" vhost

### ISSUE THREAD

**Issue by nevesing** [reportportal/service-api#1971]
I am trying to use external rabbitmq instance where we dont have access to `/` vhost and our internal team who host this rabbitmq instance do not provide access to `/` vhost. We configure `RP_AMQP_ANALYZER-VHOST` to specific vhost but still it tries to connect to additional vhost `/`

```yml
  api:
    image: docker-hub-remote.artifactory.teslamotors.com/reportportal/service-api:5.11.0
    container_name: reportportal-api
    logging:
      <<: *logging
    depends_on:
      # rabbitmq:
      #   condition: service_healthy
      gateway:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      RP_DB_HOST: *db_host
      RP_DB_USER: *db_user
      RP_DB_PASS: *db_password
      RP_DB_NAME: *db_name
      RP_AMQP_HOST: rabbitmq-external.xxx.com
      RP_AMQP_PORT: 5672
      RP_AMQP_USER: reportportaladmusr
      RP_AMQP_PASS: xxx
      RP_AMQP_APIUSER: reportportaladmusr
      RP_AMQP_APIPASS: xxx
      RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal
      DATASTORE_TYPE: filesystem
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: debug
      RP_REQUESTLOGGING: "false"
      AUDIT_LOGGER: "OFF"
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
      RP_ENVIRONMENT_VARIABLE_ALLOW_DELETE_ACCOUNT: "false"
      LOGGING_LEVEL_COM_EPAM_TA_REPORTPORTAL_WS_CONTROLLER: debug
      LOGGING_LEVEL_COM_EPAM_TA_REPORTPORTAL_WS_RABBIT: debug
      JAVA_OPTS: >
        -Xmx1g 
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/tmp  
        -Dcom.sun.management.jmxremote.rmi.port=12349 
        -Dcom.sun.management.jmxremote 
        -Dcom.sun.management.jmxremote.local.only=false  
        -Dcom.sun.management.jmxremote.port=9010 
        -Dcom.sun.management.jmxremote.authenticate=false 
        -Dcom.sun.management.jmxremote.ssl=false 
        -Djava.rmi.server.hostname=0.0.0.0
      RP_JOBS_BASEURL: http://jobs:8686
      COM_TA_REPORTPORTAL_JOB_INTERRUPT_BROKEN_LAUNCHES_CRON: PT1H
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_BATCH-SIZE: 100
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_PREFETCH-COUNT: 1
      RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_CONSUMERS-COUNT: 1
    volumes:
      - storage:/data/storage
    healthcheck:
      test: curl -f http://0.0.0.0:8585/health
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip-prefix@docker"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8585"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    networks:
      - reportportal
    restart: always
```

Error logs if we use external hosted rabbitmq:

```
reportportal-api  | Caused by: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - access to vhost '/' refused for user 'reportportaladmusr', class-id=10, method-id=40)
```

Success logs if we use internal rabbitmq in docker--compose:

```
reportportal-api  | 2024-04-16 11:28:59.875  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: connectionFactory#1d8e9f22:0/SimpleConnection@29a73056 [delegate=amqp://rabbitmq@172.26.0.3:5672/, localPort= 54540]

...

reportportal-api  | 2024-04-16 11:29:44.783  INFO 1 --- [nio-8585-exec-1] o.s.a.r.c.CachingConnectionFactory       : Created new connection: analyzerConnectionFactory#2f19ab6:0/SimpleConnection@748feadf [delegate=amqp://rabbitmq@172.26.0.3:5672/fs-qa-reportportal, localPort= 54610]
```

**Comment by Pink-Bumblebee** [comment]
@nevesing , actually I do not understand why you need external Rabbit.

**Comment by nevesing** [comment]
> @nevesing , actually I do not understand why you need external Rabbit. Could you please explain?

I mean a managed rabbitmq instance which is not part of the docker-compose services. I use that instance for other projects and so want to use the same for reportportal.

**Comment by nevesing** [comment]
Below is from a k8s deployment using helmchart. Rabbitmq is deployed with same helm chart and I still see below errors relevant to `/` vhost however everything is working fine. My goal is to use on-prem rabbitmq instance as mentioned above

```
itmq@192.168.31.109:5672/,133), conn: Proxy@3aef4650 Shared Rabbit Connection: SimpleConnection@21df2968 [delegate=amqp://rabbitmq@192.168.31.109:5672/, localPort= 48556], acknowledgeMode=AUTO local queue size=0
2024-04-18 16:17:42.520  INFO 1 --- [168.31.109:5672] o.s.a.r.c.CachingConnectionFactory       : Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - queue 'reporting.1' in vhost '/' in exclusive use, class-id=60, method-id=20)
2024-04-18 16:17:47.523  WARN 1 --- [.Spring.bean-10] o.s.a.r.l.SimpleMessageListenerContainer : Exclusive consumer failure: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - queue 'reporting.1' in vhost '/' in exclusive use, class-id=60, method-id=20)
2024-04-18 16:17:47.525  INFO 1 --- [.Spring.bean-10] c.e.t.r.ws.rabbit.ConsumerEventListener  : Restarting consumer with a queue reporting.0
2024-04-18 16:17:47.527  INFO 1 --- [.Spring.bean-10] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@12e178aa: tags=[[]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@192.168.31.109:5672/,135), conn: Proxy@3aef4650 Shared Rabbit Connection: SimpleConnection@21df2968 [delegate=amqp://rabbitmq@192.168.31.109:5672/, localPort= 48556], acknowledgeMode=AUTO local queue size=0
2024-04-18 16:20:02.289  INFO 1 --- [_ClusterManager] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: detected 1 failed or restarted instances.
```

**Comment by raikbitters** [comment]
@nevesing hello. Could you try to set with variable for API Service: `RP_AMQP_BASE-VHOST: /your-host/` ?

**Comment by raikbitters** [comment]
> I tried as per your suggestion. I set `RP_AMQP_BASE-VHOST` and `RP_AMQP_ANALYZER-VHOST` both to same value `fs-qa-reportportal-vh`.

We use different vhosts for API and Analyzer. For that reason could you create different vhosts for API service and Analyzer?

**Comment by raikbitters** [comment]
> It fails with unauthorized error because it is trying to create that vhost i believe

Yes, it's correct. The service API uses the RabbitMQ manage API endpoint you provide here, `RP_AMQP_API-ADDRESS,` to create a vhost for Service Analyzer with a name you provide here, `RP_AMQP_ANALYZER-VHOST.` It's a comment behavior, and you can change that. You have to provide credentials for RabbitMQ manage API here `RP_AMQP_API-ADDRESS`.

**Comment by nevesing** [comment]
Thanks @raikbitters. I see the same error "Not administrator user" and my changes are below. API credentials are correct otherwise we will not see this error. It is still trying to create`fs-qa-reportportal-analyzer-vh` and the PUT fails. The on-prem instance already has both the vhosts created and access granted for same user. Please help.

```yml
RP_AMQP_API-ADDRESS: https://xxx:xxxx@rabbitmq-external-console.xxx.com/api
RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal-analyzer-vh
RP_AMQP_BASE-VHOST: fs-qa-reportportal-api-vh
```

**Comment by nevesing** [comment]
@raikbitters could you suggest other workarounds/solution?

**Comment by raikbitters** [comment]
> Thanks @raikbitters. I see the same error "Not administrator user" and my changes are below. API credentials are correct otherwise we will not see this error. It is still trying to create`fs-qa-reportportal-analyzer-vh` and the PUT fails. The on-prem instance already has both the vhosts created and access granted for same user. Please help.
> 
> ```yaml
> RP_AMQP_API-ADDRESS: https://xxx:xxxx@rabbitmq-external-console.xxx.com/api
> RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal-analyzer-vh
> RP_AMQP_BASE-VHOST: fs-qa-reportportal-api-vh
> ```

@nevesing hello. Did you provide credentials for admin user?

**Comment by nevesing** [comment]
> > Thanks @raikbitters. I see the same error "Not administrator user" and my changes are below. API credentials are correct otherwise we will not see this error. It is still trying to create`fs-qa-reportportal-analyzer-vh` and the PUT fails. The on-prem instance already has both the vhosts created and access granted for same user. Please help.
> > ```yaml
> > RP_AMQP_API-ADDRESS: https://xxx:xxxx@rabbitmq-external-console.xxx.com/api
> > RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal-analyzer-vh
> > RP_AMQP_BASE-VHOST: fs-qa-reportportal-api-vh
> > ```
> 
> @nevesing hello. Did you provide credentials of admin user?

@raikbitters yes the admin credentials I used is for the vhosts (fs-qa-reportportal-analyzer-vh and fs-qa-reportportal-api-vh) only (not for the entire managed rabbitmq instance)

**Comment by nevesing** [comment]
`fs-qa-reportportal-analyzer-vh` shows these queues but nothing for `fs-qa-reportportal-api-vh`

![image](https://github.com/reportportal/service-api/assets/50423486/ed5c5266-af63-4063-aaf2-644a1827a57f)

**Comment by nevesing** [comment]
```
reportportal-jobs  | Caused by: com.rabbitmq.http.client.HttpClientException: PUT returned 401
reportportal-jobs  | 	at com.rabbitmq.http.client.JdkHttpClientHttpLayer.maybeThrowClientServerException(JdkHttpClientHttpLayer.java:128) ~[http-client-5.2.0.jar!/:5.2.0]
reportportal-jobs  | 	at com.rabbitmq.http.client.JdkHttpClientHttpLayer.put(JdkHttpClientHttpLayer.java:208) ~[http-client-5.2.0.jar!/:5.2.0]
reportportal-jobs  | 	at com.rabbitmq.http.client.Client.createVhost(Client.java:378) ~[http-client-5.2.0.jar!/:5.2.0]
reportportal-jobs  | 	at com.epam.reportportal.analyzer.RabbitMqManagementClientTemplate.<init>(RabbitMqManagementClientTemplate.java:48) ~[classes!/:na]
reportportal-jobs  | 	at com.epam.reportportal.config.rabbit.AnalyzerRabbitMqConfiguration.managementTemplate(AnalyzerRabbitMqConfiguration.java:64) ~[classes!/:na]
reportportal-jobs  | 	at com.epam.reportportal.config.rabbit.AnalyzerRabbitMqConfiguration$$EnhancerBySpringCGLIB$$9619fcd1.CGLIB$managementTemplate$2(<generated>) ~[classes!/:na]
reportportal-jobs  | 	at com.epam.reportportal.config.rabbit.AnalyzerRabbitMqConfiguration$$EnhancerBySpringCGLIB$$9619fcd1$$FastClassBySpringCGLIB$$da2f2ae2.invoke(<generated>) ~[classes!/:na]
reportportal-jobs  | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.30.jar!/:5.3.30]
reportportal-jobs  | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.30.jar!/:5.3.30]
reportportal-jobs  | 	at com.epam.reportportal.config.rabbit.AnalyzerRabbitMqConfiguration$$EnhancerBySpringCGLIB$$9619fcd1.managementTemplate(<generated>) ~[classes!/:na]
reportportal-jobs  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
reportportal-jobs  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
reportportal-jobs  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.30.jar!/:5.3.30]
reportportal-jobs  | 	... 40 common frames omitted
reportportal-jobs  |
```

**Comment by nevesing** [comment]
Compose file for api and job service:

```yaml
api:
  image: reportportal/service-api:5.11.1
  container_name: reportportal-api
  logging:
    <<: *logging
  depends_on:
    gateway:
      condition: service_started
    postgres:
      condition: service_healthy
  environment:
    RP_DB_HOST: postgres
    RP_DB_USER: *db_user
    RP_DB_PASS: *db_password
    RP_DB_NAME: *db_name
    RP_AMQP_HOST: &rabbitmq_host rabbitmq-external.xxx.com
    RP_AMQP_API-ADDRESS: &rabbitmq_api_host https://admin:xxxx@rabbitmq-external-console.xxx.com/api
    RP_AMQP_PORT: &rabbitmq_port 5672
    RP_AMQP_USER: &rabbitmq_user admin
    RP_AMQP_PASS: &rabbitmq_password xxxx
    RP_AMQP_APIUSER: *rabbitmq_user
    RP_AMQP_APIPASS: *rabbitmq_password
    RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal-analyzer-vh
    RP_AMQP_BASE-VHOST: fs-qa-reportportal-api-vh
    DATASTORE_TYPE: filesystem
    LOGGING_LEVEL_ORG_HIBERNATE_SQL: debug
    RP_REQUESTLOGGING: "false"
    AUDIT_LOGGER: "OFF"
    MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
    RP_ENVIRONMENT_VARIABLE_ALLOW_DELETE_ACCOUNT: "false"
    LOGGING_LEVEL_COM_EPAM_TA_REPORTPORTAL_WS_CONTROLLER: debug
    LOGGING_LEVEL_COM_EPAM_TA_REPORTPORTAL_WS_RABBIT: debug
    JAVA_OPTS: >
      -Xmx1g 
      -XX:+HeapDumpOnOutOfMemoryError 
      -XX:HeapDumpPath=/tmp  
      -Dcom.sun.management.jmxremote.rmi.port=12349 
      -Dcom.sun.management.jmxremote 
      -Dcom.sun.management.jmxremote.local.only=false  
      -Dcom.sun.management.jmxremote.port=9010 
      -Dcom.sun.management.jmxremote.authenticate=false 
      -Dcom.sun.management.jmxremote.ssl=false 
      -Djava.rmi.server.hostname=0.0.0.0
    RP_JOBS_BASEURL: http://jobs:8686
    COM_TA_REPORTPORTAL_JOB_INTERRUPT_BROKEN_LAUNCHES_CRON: PT1H
    RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_BATCH-SIZE: 100
    RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_PREFETCH-COUNT: 1
    RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_CONSUMERS-COUNT: 1
  volumes:
    - storage:/data/storage
  healthcheck:
    test: curl -f http://0.0.0.0:8585/health
    interval: 60s
    timeout: 30s
    retries: 10
    start_period: 60s
  labels:
    - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api"
    - "traefik.http.routers.api.middlewares=api-strip-prefix@docker"
    - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
    - "traefik.http.routers.api.service=api"
    - "traefik.http.services.api.loadbalancer.server.port=8585"
    - "traefik.http.services.api.loadbalancer.server.scheme=http"
    - "traefik.expose=true"
  networks:
    - reportportal
  restart: always

jobs:
  image: reportportal/service-jobs:5.11.1
  container_name: reportportal-jobs
  logging:
    <<: *logging
  depends_on:
    gateway:
      condition: service_started
  environment:
    RP_DB_HOST: postgres
    RP_DB_USER: *db_user
    RP_DB_PASS: *db_password
    RP_DB_NAME: *db_name
    RP_AMQP_HOST: *rabbitmq_host
    RP_AMQP_PORT: *rabbitmq_port
    RP_AMQP_USER: *rabbitmq_user
    RP_AMQP_PASS: *rabbitmq_password
    RP_AMQP_API-ADDRESS: *rabbitmq_api_host
    RP_AMQP_APIUSER: *rabbitmq_user
    RP_AMQP_APIPASS: *rabbitmq_password
    RP_AMQP_ANALYZER-VHOST: fs-qa-reportportal-analyzer-vh
    RP_AMQP_BASE-VHOST: fs-qa-reportportal-api-vh
    DATASTORE_TYPE: filesystem
    RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON: 0 0 */24 * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON: 0 0 */24 * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON: 0 0 */24 * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON: 0 0 */24 * * *
    RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON: 0 */5 * * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_EXPIREDUSER_CRON:  0 0 */24 * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_EXPIREDUSER_RETENTIONPERIOD: 365
    RP_ENVIRONMENT_VARIABLE_NOTIFICATION_EXPIREDUSER_CRON: 0 0 */24 * * * 
    RP_ENVIRONMENT_VARIABLE_CLEAN_EVENTS_RETENTIONPERIOD: 365
    RP_ENVIRONMENT_VARIABLE_CLEAN_EVENTS_CRON: 0 30 05 * * *
    RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE: 20000
    RP_PROCESSING_LOG_MAXBATCHSIZE: 2000
    RP_PROCESSING_LOG_MAXBATCHTIMEOUT: 6000
    RP_AMQP_MAXLOGCONSUMER: 1
    JAVA_OPTS: >
      -Djava.security.egd=file:/dev/./urandom
      -XX:+UseG1GC
      -XX:+UseStringDeduplication
      -XX:G1ReservePercent=20
      -XX:InitiatingHeapOccupancyPercent=60
      -XX:MaxRAMPercentage=70.0
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/tmp
  volumes:
    - storage:/data/storage
  healthcheck:
    test: curl -f http://0.0.0.0:8686/health || exit 1
    interval: 60s
    timeout: 30s
    retries: 10
    start_period: 60s
  labels:
    - traefik.http.middlewares.jobs-strip-prefix.stripprefix.prefixes=/jobs
    - traefik.http.routers.jobs.middlewares=jobs-strip-prefix@docker
    - traefik.http.routers.jobs.rule=PathPrefix(`/jobs`)
    - traefik.http.routers.jobs.service=jobs
    - traefik.http.services.jobs.loadbalancer.server.port=8686
    - traefik.http.services.jobs.loadbalancer.server.scheme=http
    - traefik.expose=true
  networks:
    - reportportal
  restart: always
```
